config/routes.rb
Rails.application.routes.draw do
  resource :sessions, only: [:new, :create, :destroy]
  resources :projects, except: :show do
    resource :stop, only: [:update, :destroy], module: :projects
  end
  resources :todos, only: :index
  resources :activities, only: :index

  namespace :api, defaults: { format: :json } do
    scope :v1 do
      resources :projects, only: [:index] do
        resources :tasks, only: [:create, :update, :destroy], shallow: true do
          resources :pomodoros, only: [:create, :update, :destroy], shallow: true
        end
      end
      namespace :projects do
        resources :in_progresses, only: [:index]
      end
      resources :todos, only: [:index]
    end
  end
end

app/views/shared/_flash.html.haml
- flash.each do |name, msg|
  - if name == 'notice'
    .alert.alert-warning
      = msg
  - elsif name == 'alert'
    .alert.alert-danger
      = msg

app/views/shared/_header.html.haml
%nav.navbar.navbar-expand-lg.navbar-light.bg-light.mb-3
  = link_to 'Pomodoro', todos_path, class: 'navbar-brand'
  - if logged_in?
    %button.navbar-toggler{"aria-controls" => "navbarNav", "aria-expanded" => "false", "aria-label" => "Toggle navigation", "data-target" => "#navbarNav", "data-toggle" => "collapse", :type => "button"}
      %span.navbar-toggler-icon
    #navbarNav.collapse.navbar-collapse
      %ul.navbar-nav.mr-auto
        %li{class: "nav-item #{'active' if controller.controller_name == 'activities'}"}
          = link_to 'アクティビティ在庫シート', activities_path, class: 'nav-link'
        %li{class: "nav-item #{'active' if controller.controller_name == 'todos'}"}
          = link_to 'TODOシート', todos_path, class: 'nav-link'
        %li{class: "nav-item #{'active' if controller.controller_name == 'projects'}"}
          = link_to 'プロジェクト管理', projects_path, class: 'nav-link'
      %ul.navbar-nav.ml-auto
        %li.nav-item
          = link_to 'Logout', sessions_path, method: :delete, class: 'nav-link'