config/routes.rb
Rails.application.routes.draw do
  resource :sessions, only: [:new, :create, :destroy]
  resources :projects, except: :show do
    resource :stop, only: [:update, :destroy], module: :projects
  end
  resources :todos, only: :index
  resources :activities, only: :index

  namespace :api, defaults: { format: :json } do
    scope :v1 do
      resources :projects, only: [:index] do
        resources :tasks, only: [:create, :update, :destroy], shallow: true do
          resources :pomodoros, only: [:create, :update, :destroy], shallow: true
        end
      end
      namespace :projects do
        resources :in_progresses, only: [:index]
      end
      resources :todos, only: [:index]
    end
  end
end

app/models/project.rb
# == Schema Information
#
# Table name: projects
#
#  id         :integer          not null, primary key
#  user_id    :integer          not null
#  name       :string(255)      not null
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  stopped_at :datetime
#  is_default :boolean          default(FALSE)
#
# Indexes
#
#  index_projects_on_stopped_at  (stopped_at)
#  index_projects_on_user_id     (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#

class Project < ApplicationRecord
  scope :without_default, -> { where(is_default: false) }
  scope :in_progress, -> { where(stopped_at: nil) }

  belongs_to :user

  has_many :tasks, dependent: :restrict_with_error

  validates :name, presence: true
  validate :cannot_stop_default_project
  validate :cannot_stop_with_tasks_after_today
  validate :cannot_be_default

  before_destroy :cannot_destroy_default_project

  def stop
    update(stopped_at: DateTime.current)
  end

  def restart
    update(stopped_at: nil)
  end

  def stopped?
    stopped_at?
  end

  private

  def cannot_destroy_default_project
    if is_default?
      errors.add(:base, 'デフォルトプロジェクトは削除できません')
      throw :abort
    end
  end

  def cannot_stop_default_project
    errors.add(:base, 'デフォルトプロジェクトは停止できません') if stopped? && is_default?
  end

  def cannot_stop_with_tasks_after_today
    errors.add(:base, '本日以降のタスクが紐づいたプロジェクトは停止できません') if stopped? && tasks.where('todo_on >= ?', Date.current).present?
  end

  def cannot_be_default
    errors.add(:is_default, 'は後から設定できません') if is_default?
  end
end

app/controllers/api/projects/in_progresses_controller.rb
class Api::Projects::InProgressesController < Api::BaseController
  def index
    @projects = Project.in_progress
  end
end

app/controllers/api/projects_controller.rb
class Api::ProjectsController < Api::BaseController
  def index
    @projects = current_user.projects.without_default
  end
end

app/controllers/projects/stops_controller.rb
class Projects::StopsController < ApplicationController
  before_action :set_project, only: [:update, :destroy]

  # TODO: 戻り値が false の処理を追加する
  def update
    @project.stop
    redirect_to projects_url, notice: 'プロジェクトが停止されました'
  end

  def destroy
    @project.restart
    redirect_to projects_url, notice: 'プロジェクトが再開されました'
  end

  private

  def set_project
    @project = current_user.projects.find(params[:project_id])
  end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :destroy]

  def index
    @projects = current_user.projects.without_default
  end

  def new
    @project = Project.new
  end

  def edit
  end

  def create
    @project = current_user.projects.new(project_params)

    if @project.save
      redirect_to projects_url, notice: 'プロジェクトが作成されました'
    else
      render :new
    end
  end

  def update
    if @project.update(project_params)
      redirect_to projects_url, notice: 'プロジェクトが更新されました'
    else
      render :edit
    end
  end

  def destroy
    if @project.destroy
      redirect_to projects_url, notice: 'プロジェクトが削除されました'
    else
      redirect_to projects_url, alert: @project.errors.full_messages.first
    end
  end

  private

  def set_project
    @project = current_user.projects.find(params[:id])
  end

  def project_params
    params.require(:project).permit(:name)
  end
end

app/views/projects/_form.html.haml
= form_for @project do |f|
  - if @project.errors.any?
    .alert.alert-danger
      - @project.errors.full_messages.each do |message|
        = message

  .form-group
    = f.label :name
    = f.text_field :name, class: 'form-control'
  = f.submit '保存', class: 'btn btn-outline-secondary mb-2'

app/views/projects/edit.html.haml
%h1 プロジェクト編集

= render 'form'

= link_to '戻る', projects_path

app/views/projects/index.html.haml
%h1.mb-3 プロジェクト一覧

%table.table.table-hover
  %tbody
    - @projects.each do |project|
      - if project.stopped?
        %tr.table-dark
          %td= project.name
          %td
            = link_to '編集', edit_project_path(project), class: 'btn btn-outline-secondary btn-sm'
            = link_to '再開', project_stop_path(project.id), method: :delete, class: 'btn btn-outline-warning btn-sm'
            = link_to '削除', project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm'
      - else
        %tr
          %td= project.name
          %td
            = link_to '編集', edit_project_path(project), class: 'btn btn-outline-secondary btn-sm'
            = link_to '停止', project_stop_path(project.id), method: :patch, class: 'btn btn-outline-warning btn-sm'
            = link_to '削除', project, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-outline-danger btn-sm'

= link_to '新規作成', new_project_path, class: 'btn btn-outline-secondary'

app/views/projects/new.html.haml
%h1 プロジェクト新規作成

= render 'form'

= link_to '戻る', projects_path